### ISSUE TITLE
未适配深色模式的几个地方

### ISSUE THREAD

**Issue by fengshuo2004** [ChenZihan-sudo/BilibiliDarkMode#1]
由衷感谢您开发了这个插件，拯救了我滴狗眼。在此反馈几个还没有改成深色的地方：

1. 新版主页动态弹框的“历史动态”四个字

![屏幕截图 2022-04-09 122939](https://user-images.githubusercontent.com/25703836/162573770-22011247-cdec-4ad6-8ce0-b0d658a05f2c.png)

2. 动态页面的这三个框框

![屏幕截图 2022-04-09 125314](https://user-images.githubusercontent.com/25703836/162573790-499df98c-5168-4566-b2ef-793b1da7f1a1.png)

4. 私信输入栏是黑底黑字，表情栏保留了原版样式

![屏幕截图 2022-04-09 123159](https://user-images.githubusercontent.com/25703836/162573806-7fc1ec73-045e-4ed4-a06e-a8d3d470d3d3.png)

麻烦您解决一下，谢谢。

**Comment by ChenZihan-sudo** [comment]
前两个我可以解决。最后一张图因为最近没有太多时间暂时不会去适配，如果想适配的话，可以自己动手来试试，在仓库有个ipynb是用来格式化css内容的。
