### ISSUE TITLE
新版评论区黑色失效

### ISSUE THREAD

**Issue by 598503227** [ChenZihan-sudo/BilibiliDarkMode#3]
亲爱的大佬 我突然发现新版的评论区黑色背景突然不适配了 切换回旧版就一切正常 希望大佬能抽出时间适配下 kisskiss
![)QMGX}A5WK(B0Q8(JMSYCMN](https://user-images.githubusercontent.com/52618424/192897605-0acf7145-86e3-4ff8-8a31-34cfe3db4291.png)

**Comment by Catcolia** [comment]
你好，该问题已经解决，请到greasyforks更新脚本，感谢发issue
